### ISSUE TITLE
Login fails on remote site (but not in local/dev site)

### ISSUE THREAD

**Issue by pr3ssh** [Wylio/meteor-mandrill#14]
Hi there!
First of all, thanks for this awesome package. I have being using in dev environment for several months and everything works fine but not in my remote site (production site). I cannot login on Mandrill and the system show me that message:

```
AuthError: Invalid login - 435 4.7.8 Error: authentication failed
```

Anybody knows what's going on? I load config data in settings.json and I use meteor-up for deploying.
Thanks!

**Comment by dandv** [comment]
Might this be [related to the capitalization of the `Key` parameter](https://github.com/Wylio/meteor-mandrill/issues/12#issuecomment-144286892)?

**Comment by pr3ssh** [comment]
@dandv thanks for your reply. Finally the problem was not related to meteor-mandrill but with the way I use for deploying (with Meteor Up). Sorry but I forgot to close that issue (fast programming facts).
