### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by CyberCyclone** [Wylio/meteor-mandrill#26]
If this package is no longer maintained, could you please put up a proper notice letting users know this? It's been 6 years since this package was lasted worked on properly and it's currently not compatible with the current version of Meteor and it's packages (the email package in particular).

Users will be better using the offical Mailchimp / Mandrill NodeJS API:
https://www.npmjs.com/package/@mailchimp/mailchimp_transactional

**Comment by dandv** [comment]
Good call.

@timmyg, can we archive this repo please?
