### ISSUE TITLE
usage with `Accounts.sendEnrollmentEmail` ?

### ISSUE THREAD

**Issue by AlexFrazer** [Wylio/meteor-mandrill#6]
I followed the quick start guide, can send an email fine. the `MAIL_URL` appears to be set fine.

My question is; how does one send a template using the `Accounts.sendEnrollmentEmail`?

**Comment by nkoren** [comment]
I'd love a quick solution to this as well. Will post it here if I write one myself.

**Comment by AlexFrazer** [comment]
If it helps, I just overrode the `Accounts.sendEnrollmentEmail` function, copied and pasted it, then added an "extraOptions" parameter that extended the email to add headers.

**Comment by dandv** [comment]
@AlexFrazer's solution is fortunately overkill.

The package has been rewritten from scratch to implement the full Mandrill API. Please see the [release notes](https://github.com/Wylio/meteor-mandrill/releases/tag/1.0.0).

The README has a section on [how to use Meteor's default Accounts.emailTemplates](https://github.com/Wylio/meteor-mandrill#using-meteors-accountsemailtemplates).
