### ISSUE TITLE
HTTP is not defined

### ISSUE THREAD

**Issue by nkoren** [Wylio/meteor-mandrill#7]
I know this shouldn't happen, because clearly the package *is* calling the http package -- but this is what I get when I try to do Mandrill.sendTemplate:

```
I20150612-10:14:48.124(1)? ReferenceError: HTTP is not defined
I20150612-10:14:48.125(1)?     at Object.Meteor.Mandrill.sendTemplate (packages/wylio:mandrill/mandrill.js:30:1)
```

This is running in debug mode on my local machine. Help?

**Comment by nkoren** [comment]
I solved this problem by manually doing "meteor add http". Looking at the package.js, this shouldn't have been necessary -- no idea why it was! But there you go.

**Comment by dandv** [comment]
The package has been rewritten from scratch to implement the full Mandrill API. Please see the [release notes](https://github.com/Wylio/meteor-mandrill/releases/tag/1.0.0).

If this HTTP error pops up again, feel free to create a new issue :)
