### ISSUE TITLE
Package still maintained?

### ISSUE THREAD

**Issue by dandv** [Wylio/meteor-mandrill#8]
I see a number of forks have cropped up:

* @dan335 - https://github.com/dan335/meteor-mandrill/pull/1
* @frozeman - https://github.com/frozeman/meteor-mandrill/pulls
* @raxraxraxraxrax - https://github.com/raxraxraxraxrax/meteor-mandrill/pull/1

Can you gentlemen please work together so that the have *one* Mandril package on Atmosphere?

I'd be happy to create a MeteorPackaging repo where folks can collaborate even if one particular maintainer can no longer afford the time to update the package.

**Comment by raxraxraxraxrax** [comment]
Not a gentleman; you might pick a different greeting. I made a fork
on github so that I could pass on a change, because that seemed to be
required; if you have a recommendation for a helpful way to delineate
or close that, I'm happy to do so.

Best,

-r.

**Comment by frozeman** [comment]
I'm happy to merge my changes into any repo, which want to maintain this package...

**Comment by dandv** [comment]
> Not a gentleman; you might pick a different greeting.

It would help to have a name on your profile, and a non-cartoon avatar. As much as I am for Women in Tech, Girls who Code, Women 2.0, non-binary gender and so on, studies show that [people want to collaborate with people, not cartoon characters](https://pinboard.in/u:dandv/t:cartoon/t:avatar), however articulate they might be.

**Comment by raxraxraxraxrax** [comment]
Thanks for the free advice! If you're not interested in collaborating
with me, please stop contacting me. 

<3,

-r.

**Comment by dandv** [comment]
I took over the package and rewrote it from scratch to implement the full Mandrill API. Thanks to @danieljonce for working with me on this one.

Please see the [release notes](https://github.com/Wylio/meteor-mandrill/releases/tag/1.0.0).

**Comment by chmac** [comment]
@dandv I would recommend "apologies, my mistake" as a more appropriate response to @raxraxraxraxrax's reply, rather than "advising" that they change their profile pic.
